sudo: required
language: generic

services:
  - docker

before_install: 
    - docker build -t wilpat/sample-app -f Dockerfile.dev .
deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'sample-docker-react'
  env: 'Sampledockerreact-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-628670420137'
  bucket_path: 'sample-docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
